apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext904.1095890410959
  labels:
    app: BoundedContext904.1095890410959
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext904.1095890410959
  template:
    metadata:
      labels:
        app: BoundedContext904.1095890410959
    spec:
      containers:
        - name: BoundedContext904.1095890410959
          image: "username/BoundedContext904.1095890410959:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
